### ISSUE TITLE
Extended objects are ignored

### ISSUE THREAD

**Issue by t-geindre** [Ponup/php-sdl#31]
I tryed to extend `\SDL_Rect` as follows:
```php
class Rect extends \SDL_Rect
{
}
```

The extended version make the following condition to consider my object as an invalid `SDL_Rect`:
https://github.com/Ponup/phpsdl/blob/master/rect.c#L74

So any call to an SDL function with an extended `SDL_Rect` always ends up with an empty `SDL_Rect`.

**Comment by santiagolizardo** [comment]
Thanks for reporting the issue @t-geindre . This has now been fixed and the code to be released in our upcoming release this month.
