### ISSUE TITLE
Just saying thanks!

### ISSUE THREAD

**Issue by GXTX** [Ponup/php-sdl#40]
I enjoyed playing around with this project and ported a simple mandelbrot fractal application to PHP (which is a wild thing to say!)

I ran into some issues while trying to manually set per-pixel which I was able to do in C (checkout the `xbox` branch or older commits in `php` for more info on that), I don't know if it was some bug with the project or me not understanding something but drawing a point works just as well.

Thanks again.

https://github.com/GXTX/mandelbrot-c-sdl2/tree/php
![image](https://user-images.githubusercontent.com/858612/77850745-77657580-71a2-11ea-9a1a-a838ff19fce0.png)

**Comment by santiagolizardo** [comment]
You are very welcome. We (@remicollet , @b-viguier, @santiagolizardo ) are glad people are having fun with this extension.
