### ISSUE TITLE
multiple definition of `php_sdl_rect_ce' bugs

### ISSUE THREAD

**Issue by dreamfly2012** [Ponup/php-sdl#45]
when i download version sdl-2.2.0, i configure it , then make it .

i met the problem such as:

/usr/bin/ld: .libs/pixels.o:/home/menghuiguli/sdl-2.2.0/pixels.h:38: multiple definition of `php_sdl_pixelformat_ce'; .libs/php_sdl.o:/home/menghuiguli/sdl-2.2.0/pixels.h:38: first defined here
/usr/bin/ld: .libs/rect.o:/home/menghuiguli/sdl-2.2.0/rect.h:30: multiple definition of `php_sdl_rect_ce'; .libs/php_sdl.o:/home/menghuiguli/sdl-2.2.0/rect.h:30: first defined here
/usr/bin/ld: .libs/render.o:/home/menghuiguli/sdl-2.2.0/rect.h:30: multiple definition of `php_sdl_rect_ce'; .libs/php_sdl.o:/home/menghuiguli/sdl-2.2.0/rect.h:30: first defined here
/usr/bin/ld: .libs/shape.o:/home/menghuiguli/sdl-2.2.0/pixels.h:39: multiple definition of `php_sdl_pixels_ce'; .libs/php_sdl.o:/home/menghuiguli/sdl-2.2.0/pixels.h:39: first defined here
/usr/bin/ld: .libs/shape.o:/home/menghuiguli/sdl-2.2.0/pixels.h:38: multiple definition of `php_sdl_pixelformat_ce'; .libs/php_sdl.o:/home/menghuiguli/sdl-2.2.0/pixels.h:38: first defined here

**Comment by remicollet** [comment]
Duplicate ot #37 fixed by PR #39

**Comment by santiagolizardo** [comment]
Thanks for reporting this @dreamfly2012 . As @remicollet pointed out, this was already fixed but it was not released until now. Try downloading the [2.4.0 package](http://pecl.php.net/package/sdl/2.4.0) and let us know if the problem reoccurs. Thanks
