### ISSUE TITLE
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'sdl.so' in Unknown on line 0

### ISSUE THREAD

**Issue by bobinmad** [Ponup/php-sdl#47]
When I include `sdl.so` in `php.ini` I get error from the title. The extension was installed like described in instruction and file
`/usr/lib/php/20190902/sdl.so` exists.

I'm running Ubuntu 20.04

**Comment by someonewithpc** [comment]
Did you compile or install with `pecl`? Can you post the ouput of `ldd $(which php)` and the `.so` file?

**Comment by santiagolizardo** [comment]
Hi @bobinmad 👋🏼 Not sure if you still want to play with this extension but if you do I am here to help you troubleshoot the issue. You might also want to try again with PHP8 and see how it goes. (PHP7 support has been removed) Thanks

**Comment by santiagolizardo** [comment]
PHP8 support has been added and released. See http://pecl.php.net/package-info.php?package=sdl&version=2.5.0
