### ISSUE TITLE
possible to add audio ?

### ISSUE THREAD

**Issue by nowburp** [Ponup/php-sdl#55]
Hi @santiagolizardo any chance you could please add the functions to load and play wav / mp3 files ?
And maybe also SDL_PointInRect, pretty please ? :)

**Comment by kea** [comment]
For audio, you can use https://github.com/Ponup/php-openal or https://github.com/kea/php-sdl-mixer

And waiting for the binding of SDL_PointInRect you can use something like
```php
function SDL_PointInRect(SDL_Point $p, SDL_Rect $r): bool
{
    return (($p->x >= $r->x) && ($p->x < ($r->x + $r->w)) &&
        ($p->y >= $r->y) && ($p->y < ($r->y + $r->h)));
}
```

**Comment by nowburp** [comment]
Thank you @kea !
php-sdl-mixer works great :)
